mysql:
  ip: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  schemas:
    - "test1"
    - "test2"
  # minute
  timeout: 2
  # id for slave conn to the mysql instance, must be unique
  id: 1
kafka:
  ip:
    - "127.0.0.1"
    - "127.0.0.2"
    - "127.0.0.3"
  port: 9092
  topic: "testTopic"